// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX5-mJIxgdnP6vpdDP3XGUd6GpzhqUneI',
    appId: '1:462816884994:web:34e583e4bb9513e184aa1b',
    messagingSenderId: '462816884994',
    projectId: 'pdv0-6be87',
    authDomain: 'pdv0-6be87.firebaseapp.com',
    storageBucket: 'pdv0-6be87.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIao7e_eckLV9g7hjniVf0hJyluNZ_7hQ',
    appId: '1:462816884994:android:04eea601573efd5984aa1b',
    messagingSenderId: '462816884994',
    projectId: 'pdv0-6be87',
    storageBucket: 'pdv0-6be87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP5fRYAKJ5Hec4J9j2S-s3qjisp1fPr4w',
    appId: '1:462816884994:ios:c0a7e73a0df5feed84aa1b',
    messagingSenderId: '462816884994',
    projectId: 'pdv0-6be87',
    storageBucket: 'pdv0-6be87.firebasestorage.app',
    iosBundleId: 'com.example.pdv0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP5fRYAKJ5Hec4J9j2S-s3qjisp1fPr4w',
    appId: '1:462816884994:ios:c0a7e73a0df5feed84aa1b',
    messagingSenderId: '462816884994',
    projectId: 'pdv0-6be87',
    storageBucket: 'pdv0-6be87.firebasestorage.app',
    iosBundleId: 'com.example.pdv0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX5-mJIxgdnP6vpdDP3XGUd6GpzhqUneI',
    appId: '1:462816884994:web:25595415a13e7c5484aa1b',
    messagingSenderId: '462816884994',
    projectId: 'pdv0-6be87',
    authDomain: 'pdv0-6be87.firebaseapp.com',
    storageBucket: 'pdv0-6be87.firebasestorage.app',
  );
}
